<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="This Package">
    <PackageVersion Include="TimeWarp.SourceGenerators" Version="$(Version)" />
  </ItemGroup>

  <ItemGroup Label="Roslyn">
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
  </ItemGroup>

  <ItemGroup Label="Code Analyzers">
    <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
  </ItemGroup>

  <ItemGroup Label="Build Tasks">
    <PackageVersion Include="TimeWarp.Build.Tasks" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup Label="Dev CLI">
    <PackageVersion Include="TimeWarp.Nuru" Version="3.0.0-beta.71" />
    <PackageVersion Include="TimeWarp.Nuru.DevCli" Version="3.0.0-beta.71" />
    <PackageVersion Include="TimeWarp.Amuru" Version="1.0.0" />
    <PackageVersion Include="TimeWarp.Amuru.Tools" Version="1.0.0-beta.2" />
    <PackageVersion Include="TimeWarp.Terminal" Version="1.0.0" />
  </ItemGroup>
</Project>
